In [ ]:
import numpy as np

## Numpy

Numpy to podstawowa biblioteka do obliczeń naukowych w Pythonie. Jeżeli masz zainstalowany interpreter Pythona i menedżer pakietów pip, to możesz zainstalować numpy za pomocą: pip install numpy. W Google Collaboratory ten pakiet jest domyślnie zainstalowany.
Podstawowym obiektem używanym w pakiecie numpy jest ndarray. Jest to wydajna wielowymiarowa tablica.

In [3]:
a = np.array([1, 2, 3])   # Tworzy tablicę wymiaru 1 o wartościcach 1, 2, 3
print(a.shape) # zwraca krotkę z rozmiarem tablicy w każdym wymiarze
print(a[0], a[1], a[2])
a[0] = 5
print(a)

print("========b========")
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1])

(3,)
1 2 3
[5 2 3]
========b========
(2, 3)
[[1 2 3]
 [4 5 6]]
1 2


Na tablicach wielowymiarowych można wykonywać operacje cięcia (slicing) jak np.:

In [16]:
b = np.array([[1,2,3],[4,5,6], [7,8,9], [10,11,12]])
print(b[0,:]) # wiersz o indeksie 0
print(b[:,0]) # kolumna o indekcie 0
print(b[1:3,:]) # wiersze od #1 do #3 (bez #3)
print(b[2:,:]) # wiersze od #2 do ostatniego
print(b[:3,:]) # wiersze od #0 do #3 (bez #3)

[1 2 3]
[ 1  4  7 10]
[[4 5 6]
 [7 8 9]]
[[ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Istnieje kilka metod pozwalających stworzyć tablice o określonych właściwościach jak np.:

In [27]:
a = np.zeros((2,2))
print(a)

b = np.ones((2,2))
print(b)

c = np.full((2,2), 3)
print(c)

d = np.eye(2)
print(d)

e = np.arange(10)
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[3 3]
 [3 3]]
[[1. 0.]
 [0. 1.]]
[0 1 2 3 4 5 6 7 8 9]


### Operacje na tablicach numpy'owych

In [25]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y) # dodawanie macierzy

print(x * y) # mnożenie tzw. element-wise

print(x @ y) # mnożenie macierzowe
print(x.dot(y)) # alternatywne mnożenie macierzowe

print(x.T) # transponowanie macierzy

print(np.sqrt(x)) # zadziałanie jakąś funkcją matematyczną przyjmującą jedną liczbę na tablicy sprawi, że zostanie zwrócony wynik na jej każdym elemencie

[[ 6.  8.]
 [10. 12.]]
[[ 5. 12.]
 [21. 32.]]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]
[[1. 3.]
 [2. 4.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


### Broadcasting
Broadcasting to potężny mechanizm, który pozwala numpy pracować z tablicami o różnych kształtach podczas wykonywania operacji arytmetycznych. Często mamy mniejszą tablicę i większą tablicę, a chcemy użyć mniejszej tablicy wiele razy, aby wykonać jakąś operację na tej większej.

In [24]:
a = np.ones((3,3))
b = np.array([1,2,3])
print(a+b)
print(b.reshape(-1,1))
print(a+b.reshape(-1,1))

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[[1]
 [2]
 [3]]
[[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


## Zadania

1. Napisz jednoargumentową funkcję w Pythonie, która będzie zwracać true, gdy liczba podana jako argument będzie pierwsza lub false w przeciwnym wypadku. Używając tej funkcji napisz list comprehention, które wygeneruje tablicę liczb pierwszych mniejszych od 100. Wskazówka: range(100) zwróci generator liczb od 0 do 99 włącznie.
2. Napisz funkcję, która dla danej tablicy numpy'owej zwróci drugą co do wielkości wartość. (Mogą się przydać takie funkcje jak np.max, czy np.where)
3. Napisz funkcję używającą numpy, która obliczy przybliżone odwrócenie macierzy korzystając z np.linalg.solve, które służy do rozwiązywania układów równań liniowych i macierzowych.
4. Używając broadcastingu napisz funkcję przyjmującą argument n, która wygeneruje tabliczkę mnożenia n na n w postaci tablicy numpy'owej.